# 配置文件加密key
jasypt:
  encryptor:
    password: tax

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://114.116.93.197:3306/tax?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://localhost:3306/tax?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    #password: ENC(ngsRLf40KOVqOJ0PatYiOQ==)
    password: Yaolong0827!
    #password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb
  #java mail
  mail:
    host: smtp.qq.com
    username: 289911401@qq.com
    password: daydayup.yao0827
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  activiti:
    history-level: full
  # 限制文件大小
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
#MyBatis配置
mybatis:
  type-aliases-package: com.chinasoft.tax.po
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: MYSQL
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=conutSql
  helper-dialect: mysql


  # Redis
  redis:
    host: localhost
    password: 123456
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000


tax:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
    # ES
  #elasticsearch:
  # nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false

  file:
    maxSize: 4194304 # 单位byte   4*1024*1024 byte
    upload: upload/
    dbFilePath: upload/db
  db:
    userName: root
    password: 123456789
    dbName: tax

# 忽略鉴权url
ignored:
  urls:
  - /tax/user/regist
  - /tax/common/**
  - /druid/**
  - /**/v2/api-docs
  - /**/*.js
  - /**/*.css
  - /**/*.png
  - /**/*.ico
  - /test/**
  - /process/**
  - /file/download/**

#  - /**
#  - /**/*
  #- /statistics/**
# 日志
logging:
  file: tax-logs/tax.log
  pattern:
  #console: "%d{ MM-dd-HH:mm:ss} %-5level %msg%n"
  level:
    com:
      chinasoft:
        tax:
          dao: debug



